### ISSUE TITLE
Just say hi

### ISSUE THREAD

**Issue by xiangming** [felixdorner/yuuta#1]
Hi Felix,

Thanks for the clean and free WordPress theme yuuta.

I have read the code, it seems you can using a WordPress theme starter framework.

Could you pls tell me what's it?

Thanks,
Arvin

**Comment by felixdorner** [comment]
Hey,

I started with [Underscores](http://underscores.me/). The theme's recent structure drifted away from Underscores which is why I didn't included it in the credits.

Cheers,
Felix
