### ISSUE TITLE
Width spreads wide

### ISSUE THREAD

**Issue by mmanishh** [felixdorner/yuuta#2]
Can u look at this post ? 

http://ktmdiaries.com/2015/12/langtang-trek/

**Comment by felixdorner** [comment]
Hey @mmanishh - thanks for using my theme. I don't get what's your issue?

**Comment by mmanishh** [comment]
Hey!
Thanks for replying. I had a post that spreads a width along instead of
wrapoing text vertically.But that post is deleted .Anyway thanks
